(function($){"use strict";var NAY={};var plugin_track='static/plugin/';$.fn.exists=function(){return this.length>0;};NAY.PreLoad=function(){document.getElementById("loading").style.display="none";}
NAY.MenuClose=function(){$('.navbar-nav a').on('click',function(){var toggle=$('.navbar-toggler').is(':visible');if(toggle){$('.navbar-collapse').collapse('hide');}});}
NAY.HeaderFixd=function(){var HscrollTop=$(window).scrollTop();if(HscrollTop>=0){$('header').addClass('fixed-header');}
else{$('header').removeClass('fixed-header');}}
NAY.OnePage=function(){$('.header-nav a[href*="#"]:not([href="#"]), .go-to a[href*="#"]:not([href="#"])').on('click',function(){if(location.pathname.replace(/^\//,'')==this.pathname.replace(/^\//,'')||location.hostname==this.hostname){var target=$(this.hash);target=target.length?target:$('[name='+this.hash.slice(1)+']');if(target.length){$('html,body').animate({scrollTop:target.offset().top-70,},1000);return false;}}});}
NAY.SearchBox=function(){var SearchToggle=$(".h_search")
SearchToggle.on("click",function(){$('.h-search-section').toggleClass("searh-form-open");});}
NAY.HeaderHeight=function(){var HHeight=$('.header-height .fixed-header-bar').height()
$('.header-height').css("min-height",HHeight);}
NAY.MegaMenu=function(){var mDropdown=$(".m-dropdown-toggle")
mDropdown.on("click",function(){$(this).parent().toggleClass("open-menu-parent");$(this).next('ul').toggleClass("open-menu");$(this).toggleClass("open");});}
NAY.Accordion=function(){$('.accordion').each(function(i,elem){var $elem=$(this),$acpanel=$elem.find(".acco-group > .acco-des"),$acsnav=$elem.find(".acco-group > .acco-heading");$acpanel.hide().first().slideDown("easeOutExpo");$acsnav.first().parent().addClass("acco-active");$acsnav.on('click',function(){if(!$(this).parent().hasClass("acco-active")){var $this=$(this).next(".acco-des");$acsnav.parent().removeClass("acco-active");$(this).parent().addClass("acco-active");$acpanel.not($this).slideUp("easeInExpo");$(this).next().slideDown("easeOutExpo");}else{$(this).parent().removeClass("acco-active");$(this).next().slideUp("easeInExpo");}
return false;});});}
NAY.Owl=function(){var owlslider=jQuery("div.owl-carousel");if(owlslider.length>0){loadScript(plugin_track+'owl-carousel/js/owl.carousel.min.js',function(){owlslider.each(function(){var $this=$(this),$items=($this.data('items'))?$this.data('items'):1,$loop=($this.attr('data-loop'))?$this.data('loop'):true,$navdots=($this.data('nav-dots'))?$this.data('nav-dots'):false,$navarrow=($this.data('nav-arrow'))?$this.data('nav-arrow'):false,$autoplay=($this.attr('data-autoplay'))?$this.data('autoplay'):true,$autospeed=($this.attr('data-autospeed'))?$this.data('autospeed'):5000,$smartspeed=($this.attr('data-smartspeed'))?$this.data('smartspeed'):1000,$autohgt=($this.data('autoheight'))?$this.data('autoheight'):false,$CenterSlider=($this.data('center'))?$this.data('center'):false,$space=($this.attr('data-space'))?$this.data('space'):30;$(this).owlCarousel({loop:$loop,items:$items,responsive:{0:{items:$this.data('xx-items')?$this.data('xx-items'):1},480:{items:$this.data('xs-items')?$this.data('xs-items'):1},768:{items:$this.data('sm-items')?$this.data('sm-items'):2},980:{items:$this.data('md-items')?$this.data('md-items'):3},1200:{items:$items}},dots:$navdots,autoplayTimeout:$autospeed,smartSpeed:$smartspeed,autoHeight:$autohgt,center:$CenterSlider,margin:$space,nav:$navarrow,navText:["<i class='ti-arrow-left'></i>","<i class='ti-arrow-right'></i>"],autoplay:$autoplay,autoplayHoverPause:true});});});}}
NAY.Gallery=function(){if($(".lightbox-gallery").exists()||$(".popup-youtube, .popup-vimeo, .popup-gmaps").exists()){loadScript(plugin_track+'magnific/jquery.magnific-popup.min.js',function(){if($(".lightbox-gallery").exists()){$('.lightbox-gallery').magnificPopup({delegate:'.gallery-link',type:'image',tLoading:'Loading image #%curr%...',mainClass:'mfp-fade',fixedContentPos:true,closeBtnInside:false,gallery:{enabled:true,navigateByImgClick:true,preload:[0,1]}});}
if($(".popup-youtube, .popup-vimeo, .popup-gmaps").exists()){$('.popup-youtube, .popup-vimeo, .popup-gmaps').magnificPopup({disableOn:700,type:'iframe',mainClass:'mfp-fade',removalDelay:160,preloader:false,fixedContentPos:false});}});}}
NAY.masonry=function(){var portfolioWork=$('.portfolio-content');if($(".portfolio-content").exists()){loadScript(plugin_track+'isotope/isotope.pkgd.min.js',function(){if($(".portfolio-content").exists()){$(portfolioWork).isotope({resizable:false,itemSelector:'.grid-item',layoutMode:'masonry',filter:'*'});var portfolioFilter=$('.filter li');$(portfolioFilter).on('click',function(){var filterValue=$(this).attr('data-filter');portfolioWork.isotope({filter:filterValue});});$(portfolioFilter).on('click',function(){$(this).addClass('active').siblings().removeClass('active');});}});}}
NAY.ProgressBar=function(){$(".skill-bar .skill-bar-in").each(function(){var bottom_object=$(this).offset().top+$(this).outerHeight();var bottom_window=$(window).scrollTop()+$(window).height();var progressWidth=$(this).attr('aria-valuenow')+'%';if(bottom_window>bottom_object){$(this).css({width:progressWidth});}});}
NAY.pieChart=function(){var $Pie_Chart=$('.pie_chart_in');if($Pie_Chart.exists()){loadScript(plugin_track+'easy-pie-chart/jquery.easypiechart.min.js',function(){$Pie_Chart.each(function(){var $elem=$(this),pie_chart_size=$elem.attr('data-size')||"160",pie_chart_animate=$elem.attr('data-animate')||"2000",pie_chart_width=$elem.attr('data-width')||"6",pie_chart_color=$elem.attr('data-color')||"#84ba3f",pie_chart_track_color=$elem.attr('data-trackcolor')||"rgba(0,0,0,0.10)";$elem.find('span, i').css({'width':pie_chart_size+'px','height':pie_chart_size+'px','line-height':pie_chart_size+'px'});$elem.appear(function(){$elem.easyPieChart({size:Number(pie_chart_size),animate:Number(pie_chart_animate),trackColor:pie_chart_track_color,lineWidth:Number(pie_chart_width),barColor:pie_chart_color,scaleColor:false,lineCap:'square',onStep:function(from,to,percent){$elem.find('span.middle').text(Math.round(percent));}});});});});}}
NAY.ContactForm=function(){$(".contactform").on("submit",function(){$(".output_message").text("Loading...");var form=$(this);$.ajax({url:form.attr("action"),method:form.attr("method"),data:form.serialize(),success:function(result){if(result=="success"){$(".contactform").find(".output_message").addClass("success");$(".output_message").text("Message Sent!");}else{$(".contactform").find(".output_message").addClass("error");$(".output_message").text("Error Sending!");}}});return false;});}
NAY.particles=function(){if($("#particles-box").exists()){loadScript(plugin_track+'particles/particles.min.js',function(){});loadScript(plugin_track+'particles/particles-app.js',function(){});}}
var $ripple_box=$('.ripple_box');NAY.ripple=function(){if($ripple_box.exists()){loadScript(plugin_track+'ripples-master/jquery.ripples.js',function(){$ripple_box.ripples({resolution:800,dropRadius:20,perturbance:0.4});});}}
var $count_timer=$('.count-down');NAY.CountTimer=function(){if($count_timer.exists()){loadScript(plugin_track+'count-down/jquery.downCount.js',function(){$count_timer.downCount({date:'12/25/2022 12:00:00',offset:-4});});}}
NAY.mTypeIt=function(){if($("#type-it").exists()){loadScript(plugin_track+'typeit-master/typeit.min.js',function(){new TypeIt('#type-it',{speed:200,loop:true,strings:['Designer','Developer'],breakLines:false});});}}
var _arr={};function loadScript(scriptName,callback){if(!_arr[scriptName]){_arr[scriptName]=true;var body=document.getElementsByTagName('body')[0];var script=document.createElement('script');script.type='text/javascript';script.src=scriptName;script.onload=callback;body.appendChild(script);}else if(callback){callback();}};$(window).on("load",function(){NAY.masonry(),NAY.PreLoad();$("#loading").delay("1000").fadeOut();});$(document).on("ready",function(){NAY.pieChart(),NAY.particles(),NAY.CountTimer(),NAY.HeaderFixd(),NAY.OnePage(),NAY.Accordion(),NAY.MenuClose(),NAY.Gallery(),NAY.SearchBox(),NAY.HeaderHeight(),NAY.MegaMenu(),NAY.ProgressBar(),NAY.mTypeIt(),NAY.ContactForm(),NAY.ripple(),NAY.Owl();});$(window).on("scroll",function(){NAY.ProgressBar(),NAY.HeaderFixd();});$(window).on("resize",function(){NAY.HeaderHeight();});document.addEventListener("DOMContentLoaded",function(){var circleProgress=(function(selector){var wrapper=document.querySelectorAll(selector);Array.prototype.forEach.call(wrapper,function(wrapper,i){var wrapperWidth,wrapperHeight,percent,innerHTML,context,lineWidth,centerX,centerY,radius,newPercent,speed,from,to,duration,start,strokeStyle,text;var getValues=function(){wrapperWidth=parseInt(window.getComputedStyle(wrapper).width);wrapperHeight=wrapperWidth;percent=wrapper.getAttribute('data-cp-percentage');innerHTML='<span class="percentage"><strong>'+percent+'</strong> %</span><canvas class="circleProgressCanvas" width="'+(wrapperWidth*2)+'" height="'+wrapperHeight*2+'"></canvas>';wrapper.innerHTML=innerHTML;text=wrapper.querySelector(".percentage");canvas=wrapper.querySelector(".circleProgressCanvas");wrapper.style.height=canvas.style.width=canvas.style.height=wrapperWidth+"px";context=canvas.getContext('2d');centerX=canvas.width/2;centerY=canvas.height/2;newPercent=0;speed=1;from=0;to=percent;duration=1000;lineWidth=25;radius=canvas.width/2-lineWidth;strokeStyle=wrapper.getAttribute('data-cp-color');start=new Date().getTime();};function animate(){requestAnimationFrame(animate);var time=new Date().getTime()-start;if(time<=duration){var x=easeInOutQuart(time,from,to-from,duration);newPercent=x;text.innerHTML=Math.round(newPercent)+" %";drawArc();}}
function drawArc(){var circleStart=1.5*Math.PI;var circleEnd=circleStart+(newPercent/50)*Math.PI;context.clearRect(0,0,canvas.width,canvas.height);context.beginPath();context.arc(centerX,centerY,radius,circleStart,4*Math.PI,false);context.lineWidth=lineWidth;context.strokeStyle="#ddd";context.stroke();context.beginPath();context.arc(centerX,centerY,radius,circleStart,circleEnd,false);context.lineWidth=lineWidth;context.strokeStyle=strokeStyle;context.stroke();}
var update=function(){getValues();animate();}
update();var btnUpdate=document.querySelectorAll(".btn-update")[0];btnUpdate.addEventListener("click",function(){wrapper.setAttribute("data-cp-percentage",Math.round(getRandom(5,95)));update();});wrapper.addEventListener("click",function(){update();});var resizeTimer;window.addEventListener("resize",function(){clearTimeout(resizeTimer);resizeTimer=setTimeout(function(){clearTimeout(resizeTimer);start=new Date().getTime();update();},250);});});function easeInOutQuart(t,b,c,d){if((t/=d/2)<1)return c/2*t*t*t*t+b;return-c/2*((t-=2)*t*t*t-2)+b;}});circleProgress('.counter');});document.addEventListener("contextmenu",(e)=>e.preventDefault());})(jQuery);